service: serverless-pdf-watermark
provider:
  name: aws
  runtime: nodejs12.x

functions:
  watermarkpdf:
    handler: handler.watermark
    events:
      - http:
          path: watermark
          method: post

plugins:
  - serverless-offline
